### ISSUE TITLE
Smallest Serviceable Slurm Substitute - Take 2

### ISSUE THREAD

**Issue by lipari** [flux-framework/distribution#18]
The following is a more selective list of features and behavior that Flux needs to support in order to replace Slurm on LC systems.  It seeks to pare https://github.com/flux-framework/distribution/issues/6 down to a more manageable level.

| Area | SLURM Functionality | Flux Requirement |
| -- | -- | -- |
| Resources | Nodes, cores, memory, GPUs, Licenses | |
| Job Request| Quantity of:  Nodes, cores, memory, GPUs, Licenses | |
| | Option to request specific nodes by name | |
| | Option for exclusive use of nodes | |
| | Node features / tags | |
| | Production or debug "queue" | |
| | Charge Account | |
| |  [WCKey](https://slurm.schedmd.com/wckey.html) | |
| | Policy override request (incl preemtable flag) | |
| | Job dependency: on success/failure of prev job(s) | |
| | Job dependency: eligible to run after specified time  | |
| | Job Name | |
| | User-supplied annotation (aka comment field) | |
| |  Specify or inherit shell limits | |
| | Specify or inherit environment variables | |
| Job Script  | directive support to convey submission options | jobspec conveys submission options and initial program arguments |
| Job type | Batch | |
| | Interactive | |
| | xterm | |
| Scheduler | Node or core-based scheduling | |
| | Backfill scheduling | | 
| | Running Job preemption | |
| Job Priority | Queue Wait time | |
| | Fair-share  | |
| | Job Size | |
| | Policy overrides (see below) | |
| Policy | User permission to charge account (forms user/account/cluster tuple) | |
| Policy: limits | Job size | |
| | Wall clock | |
| | Running Jobs per User | | 
| |  Running Jobs per Node | |
| Policy: Limit Scope | Per User / Charge Account / Cluster (most granular) | 
| | Per Charge Account / Cluster || 
| | Per "Queue" / Cluster | | 
| Policy: Overrides | exempt: exempt from limits, normal job priority ||
| | expedite: exempt from limits, increased job priority | |
| | standby: exempt from limits, very low priority, preempt-able | |
| | default: no overrides | |
| Allocate nodes, cores, memory, GPUs, Licenses |||
| Reserve nodes, cores, memory, GPUs, Licenses for Dedicated Application Times |||
| srun replacement:  Launch tasks across nodes, cores, memory, GPUs |||
| Constrain tasks to nodes, cores, memory, GPUs |||
| Status Command: resource display | State (Up, Down, Draining, etc.) ||
| | Allocated Jobs ||
| | "queue" ||
| Status Command: Job Display - one job per line OR detailed display of all fields | Job Request (all job request fields defined above) || 
| | User || 
| | State (Queued , Running , etc.) | |
| | Reason not running | | 
| | Times:  submit, eligible, start, end | | 
| | Job priority components | | 
| | Exit status  Signal number (if signaled) | | 
| Behavior |  Options for Mail at job start, end, and failure | |
| | Option to hold and release a queued job | | 
| | Option to signal and cancel job | | 
| | Option to cancel job or keep alive following resource failure | | 
| | Option to requeue job following resource failure | | 
| | Option to attach / debug running program | | 
| | Option to specify output and error files | | 
| | Prolog and Epilog for each job | |
| | Get remaining time API | |
|  Database Maintains for each Cluster: Charge Account hierarchy and user permissions | User access control (unable to submit job without an authorized charge account) | | 
| | Promised shares of resources (cpu cycles) | |
| | Limits (job size, wall clock, and running job) | |
| | Policy overrides | | 
| Database Maintains for each Cluster | Job statistics for every job ||
| | Node state changes with reasons for entering failed state | | 
| | Tracks the Workload Characterization Keys | | 
| | Defines the Operator, Coordinator, and Admin Roles | | 
| Accounting | Report job usage by user/account over requested period ||
| | Report job usage by user/account by job size over requested period | |
| | Report job usage by user/WCkey over requested period ||
| | Report machine utilization over requested period ||

**Comment by garlick** [comment]
> Job Script Support
> directive support to convey submission options

In Flux the jobscript encapsulates the submission options and the initial program arguments, so presumably that covers this requirement (sort of inside out)?

**Comment by lipari** [comment]
> In Flux the jobspec encapsulates the submission options and the initial program arguments, so presumably that covers this requirement (sort of inside out)?

Yes, I see your point.  However, this exposes a requirement that I neglected to include: compatibility with Slurm job scripts.  Users will require a means for Flux to process their legacy job scripts with minimal thought expended.

**Comment by garlick** [comment]
We should be clear on whether backwards compatibility, site-specific documentation, user-reeducation and the like are in or out of scope for the slurm replacement milestone.  My vote would be to keep the milestone focused on equivalent functionality.

**Comment by garlick** [comment]
Can an "xterm job" be covered by a generic port forwarding feature similar to ssh?

This reminds me that we need `srun --pty` equivalent.

Should we turn the description of this issue into a table where we put the requirement slurm terms on the right and Flux terms on the right on the right?

**Comment by grondo** [comment]
> Should we turn the description of this issue into a table where we put the requirements in slurm terms on the left and Flux terms on the right?

That is a great idea.

>  My vote would be to keep the milestone focused on equivalent functionality.

Another good point and I agree. There is always a way if you have equivalent functionality to create wrapper or conversion scripts, or better yet educate or offer conversion services.

**Comment by garlick** [comment]
If @lipari thinks that is a reasonable approach, I'm happy to do the table reformat.

**Comment by grondo** [comment]
I think the table will ease the creation of actual work items, which can then be encapsulated as issues in the respective projects where possible and appropriate.

**Comment by garlick** [comment]
@lipari I have this half done - I'm going to assume you're OK with it and will write it out shortly before I lose it.  If you object speak now?

**Comment by lipari** [comment]
Sorry for going dark.  I had two con calls back to back, and there were problems with email coming into the lab so I did not catch the discussion going on.

Totally OK with the table format.  Going forward, feel free to edit the table as appropriate.

The xterm requirement is marginal and could conceivably be covered under the case of an interactive job.  I mentioned it as a placeholder in case there is unique functionality available from our "mxterm" script that salloc cannot provide.

Also, I did not attempt to delve into specifying the srun replacement or any of its options like task distribution and the `--pty` you mentioned.  I just left it as a high-level mention.

**Comment by dongahn** [comment]
This is excellent. Thanks @lipari for putting this together!

**Comment by morrone** [comment]
Maybe this would be better as a wiki page?  That would be something we could all edit and work on over time instead of adding new issues for each revision.

**Comment by garlick** [comment]
I'm not opposed to that especially if we don't have to reformat the table.

Note however we all _can_ edit the description of this issue, and the suggestion was to link issues in flux-core and flux-sched for each requirement as they become more clear, not create issues for each change in the requirements...

**Comment by morrone** [comment]
Well, we already have two different issues on this same topic (your issue #6), and I don't see any way to edit the initial comment on either of them.  Perhaps you have super user privileges in this project that not everyone has?  And while having individual issues is good, it would be really good to have the table updated to include pointers rather than just having github references so we have to guess which things go with which, and what still needs to be done.

**Comment by grondo** [comment]
We could keep a more detailed table on the wiki page, including an actual specification for each component/feature we're replacing. This could be used to make a test spec for passing the milestone (even if it is manually done at first), and in its eventual form the table could make a nice guide for users.

**Comment by garlick** [comment]
On the permissions issue: looks like this project was created without any teams access?
I added the "core" team that was used for the other projects in flux-framework so hopefully people can edit the wiki and issue descriptions, etc..  Sorry about that!

**Comment by morrone** [comment]
Great, thanks!  Yes, the same markdown works in the wiki, so it was a simple cut-and-paste to start the wiki page:  https://github.com/flux-framework/distribution/wiki/Smallest-Serviceable-Slurm-Substitute-(S4)

The wiki engine does make the revision history easily available right under the page title.

**Comment by garlick** [comment]
Having the revision history is a big improvement over editing issue descriptions!

**Comment by SteVwonder** [comment]
Note from today's group meeting:
Flux should support/emulate/replace cluster partitions (batch vs debug) (cpu vs gpu/phi).  @dongahn suggested that this could be accomplished with hierarchical scheduling. @morrone suggested that this could be accomplished with our resource/job spec. @trws added that this could be accomplished with aliases in the resource/job spec.

**Comment by dongahn** [comment]
@SteVwonder: Thank you for capturing this discussion!

**Comment by garlick** [comment]
Closing this issue to avoid confusion.  The S4 table is on the wiki now, go [there](https://github.com/flux-framework/distribution/wiki/Smallest-Serviceable-Slurm-Substitute-(S4)).

**Comment by marceloamaral** [comment]
Which of the SLURM Functionalities are already supported by Flux? 
Shouldn't it be a column in the table?
