### ISSUE TITLE
subsume flux-plans with the distribution repo

### ISSUE THREAD

**Issue by garlick** [flux-framework/distribution#2]
Consider pulling in the [single wiki document](https://github.com/flux-framework/flux-plans/wiki/s4) in the flux-plans repo as an issue(?) here, and removing flux-plans as it is not being used.

**Comment by trws** [comment]
Perhaps as a set of issues under the stable 1.0 milestone? (which should also probably be headed here with branches elsewhere)

**Comment by garlick** [comment]
I transferred the document to issue #6 and removed the repo.   I'll close this one and further discussion can take place in #6
